### ISSUE TITLE
error on restart

### ISSUE THREAD

**Issue by philippfrenzel** [morozovsk/yii2-websocket#2]
PHP Warning 'yii\base\ErrorException' with message 'posix_kill() expects parameter 2 to be long, string given'

in /app/vendor/morozovsk/websocket/Server.php:111

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'posix_kill() ex...', '/app/vendor/mor...', 111, Array)
#1 /app/vendor/morozovsk/websocket/Server.php(111): posix_kill('182', 'SIGTERM')
#2 /app/vendor/morozovsk/websocket/Server.php(133): morozovsk\websocket\Server->stop()
#3 [internal function]: morozovsk\websocket\Server->restart()

**Comment by morozovsk** [comment]
это что-то уже очень давнишнее, сейчас в коде posix_kill($pid, SIGTERM) , а SIGTERM - это константа равная 15
