### ISSUE TITLE
Не хватает файлов.

### ISSUE THREAD

**Issue by ADalles** [morozovsk/yii2-websocket#4]
Здравствуйте уважаемый автор.
Не подскажете в чем может быть проблема.
Я в свой проект на Yii2 добавляю в  секцию "require" файла composer.json
следующий код.

```
"require": {
       .......
        "morozovsk/yii2-websocket": "*"
    },
```

И composer создает папку в vendor "morozovsk/yii2-websocket" вот с таким содержанием:

```

README.md
composer.json

```

других файлов там нет. Я могу в ручную добавить файлы но это не выход. Хотелось бы загрузить через composer. Не подскажете как мне это можно сделать?

PS: Даже в пустой папке просто выполнение в консоли "composer require morozovsk/yii2-websocket" возвращает тот же результат в папке присутствуют только 2 файла.

Спасибо за разъяснения по websocket было очень полезно.

**Comment by morozovsk** [comment]
здравствуйте. спасибо за фидбек. исправил. в версии 1.0.1 все файлы
