### ISSUE TITLE
Почему то не отрабатывает.

### ISSUE THREAD

**Issue by Sirgalas** [morozovsk/yii2-websocket#5]
Сразу оговорюсь только учусь причем все дается тяжело для проверки работы вашего дополнения попытался подключить так console/config/main.php 

```
'websocket' => [
            'class' => 'morozovsk\yii2websocket\Connection',
            'servers' => [
                'chat3' => [
                    'class' => 'console\models\Chat3WebsocketDaemonHandler',
                    'pid' => '/tmp/websocket_chat.pid',
                    'websocket' => 'tcp://127.0.0.1:8004',
                    'localsocket' => 'tcp://127.0.0.1:8010',
                    //'master' => 'tcp://127.0.0.1:8020',
                    //'eventDriver' => 'event'
                ]
            ],
        ],
```

сам этот класс взял у вас от сюда https://github.com/morozovsk/websocket/wiki но чутка видоизменил на такой 

```
<?php
namespace console\models;
class Chat3WebsocketDaemonHandler extends \morozovsk\websocket\Daemon
{
    protected function onOpen($connectionId, $info) {
        //call when new client connect to server
        $message ="yes";
    }

    protected function onClose($connectionId) {
        //call when existing client close connection
    }

    protected function onMessage($connectionId, $data, $type) {
        //call when new message from existing client

        $message = "user #{$connectionId}: $data";

        //send message to all client
        foreach ($this->clients as $clientId => $client) {
            $this->sendToClient($clientId, $message);
        }
    }
}
```

теперь пытаюсь запустить так ./yii websocket/start chat3 и реакция не то что бы нулевая но вот такая реакция
https://www.dropbox.com/s/1lzlk88k07a8jto/%D0%92%D1%8B%D0%B4%D0%B5%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_001.png?dl=0
а если я начинаю писать то вот так http://dl.dropbox.com/u/136642679/%D0%92%D1%8B%D0%B4%D0%B5%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_002.png я понимаю что этот чат должен не так работать может подскажите где я чего на тупил

**Comment by morozovsk** [comment]
По первой картинке видно, что команда запуска была написана правильно только с третьего раза.
По второй ссылке ничего не видно, потому что она неправильно расшарена и дропбокс выдаёт: Error (403)

**Comment by Sirgalas** [comment]
https://www.dropbox.com/s/vqacbr5l76ykntn/%D0%92%D1%8B%D0%B4%D0%B5%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_002.png?dl=0 попробуйте снова забыл  расшарить картинку. Не то что бы с третьего я уже как только не пытался просто. Первая строка это вообще не к тому. Да и потом я учусь :) Я думаю пока учишься можно совершать ошибки.

**Comment by morozovsk** [comment]
не понятно зачем было добавлено в коде: $message ="yes";
а также откуда в консоль пишет "hello test", если в коде нигде нет такой фразы
Примеры на любой вкус можно найти здесь: https://github.com/morozovsk/websocket-examples

**Comment by Sirgalas** [comment]
Hello test это сообщение пользователя то есть я сам в консоле набирал. Ну я не видел ваших примеров думал что onStart должен что то выводить при подключении.
