### ISSUE TITLE
how do i send msg to client in console controller

### ISSUE THREAD

**Issue by yumin5723** [morozovsk/yii2-websocket#6]
hi,i use your yii2-websocket project,how do i send msg to client in console controller?thanks

**Comment by morozovsk** [comment]
for example: https://github.com/morozovsk/websocket-examples/tree/master/chat3/server

**Comment by pro-sunny** [comment]
I have the same question. I've moved send.php to a separate directory to have an ability call it easily and after executing send.php, connection is established correctly however message is not show up. 
1) Should send.php be executed via yii? 
2) What could be the reason of message to  not show up anywhere?

**Comment by morozovsk** [comment]
в этом вопросе нет никакой информации, а её нужно много :)
1) sent.php - это только пример, какая строчка использовалась для отправки сообщения
2) какой она вернула результат
3) на правильный ли сокет отправлялась информация
4) какой код вебсокет клиент использовался (т.е. обработчик)
5) клиенту не пришло сообщение, но пришло ли оно в в обработчик локального сокета

**Comment by pro-sunny** [comment]
Спасибо за Ваши вопросы, пока искал на них ответы, нашел в чем была проблема :)
А она оказалась в том что для теста я использовал сервер чата, а он разрешал отправлять сообщения только авторизированным пользователям. Ну и подключение к потоку я сделал уже через yii2websocket\Connection.
Спасибо еще раз за уделенное время и за хорошую библиотеку :)
